export const getBooksBackup = () => {
	const books = {
		0: {
			author: "Edwidge Danticat",
			currency: "€",
			date: "2013",
			genre: ["fiction"],
			id: "0",
			image: "https://images-na.ssl-images-amazon.com/images/I/51FR9xhv3uL._SX322_BO1,204,203,200_.jpg",
			price: 24.9,
			title: "Claire of the sea light",
		},
		1: {
			author: "Vicente Molina Foix",
			currency: "€",
			date: "2019",
			genre: ["cinema"],
			id: "1",
			image: "https://imagessl7.casadellibro.com/a/l/t5/97/9788433916297.jpg",
			price: 8.90,
			title: "Kubrick en casa",
		},
		2: {
			author: "Dan Brown",
			currency: "€",
			date: "2013",
			genre: ["novel"],
			id: "2",
			image: "https://static1planetadelibroscom.cdnstatics.com/usuaris/libros/fotos/291/m_libros/portada_origen_dan-brown_201812262335.jpg",
			price: 12.95,
			title: "Origen",
		},
		3: {
			author: "Antonio Iturbe",
			currency: "€",
			date: "2013",
			genre: ["drama"],
			id: "3",
			image: "https://images-na.ssl-images-amazon.com/images/I/51WZ1-hfixL._SX330_BO1,204,203,200_.jpg",
			price: 9.45,
			title: "La bibliotecaria de Auschwitz",
		},
		4: {
			author: "Carmen Mola",
			currency: "€",
			date: "2019",
			genre: ["novel"],
			id: "4",
			image: "https://imagessl2.casadellibro.com/a/l/t5/72/9788420435572.jpg",
			price: 18.90,
			title: "La red púrpura",
		},
		5: {
			author: "Victor Frankl",
			currency: "€",
			date: "2015",
			genre: ["psychology", "novel"],
			id: "5",
			image: "https://images-na.ssl-images-amazon.com/images/I/51FK1XAlsYL._SX324_BO1,204,203,200_.jpg",
			price: 12.25,
			title: "El hombre en busca de sentido",
		}
	}
	return books
}